name:                polysemy
version:             1.9.0.0
github:              "polysemy-research/polysemy"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "https://funprog.zulipchat.com/#narrow/stream/216942-Polysemy"
copyright:           "2019-2023 The Polysemy Lounge"
build-type:          Custom

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Higher-order, low-boilerplate free monads.
category:            Language

description:         Please see the README on GitHub at <https://github.com/polysemy-research/polysemy#readme>

dependencies:
- base
- containers
- mtl
- syb
- stm
- template-haskell
- th-abstraction
- transformers
- first-class-families 
- unagi-chan
- async
- type-errors

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest

default-extensions:
  - BlockArguments
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - UnicodeSyntax

when:
  - condition: impl(ghc < 8.6)
    default-extensions:
      - MonadFailDesugaring
      - TypeInType

library:
  ghc-options: -Wall
  source-dirs: src
  other-modules: Polysemy.Internal.PluginLookup
  generated-other-modules:
  - Paths_polysemy

  when:
    - condition: impl(ghc < 8.2.2)
      dependencies:
        - unsupported-ghc-version > 1 && < 1

tests:
  polysemy-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy
    - inspection-testing
    - hspec
    - doctest
    - hspec-discover
    generated-other-modules:
    - Build_doctests

