name:                polysemy-plugin
version:             0.4.4.0
github:              "polysemy-research/polysemy"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"
build-type:          Custom

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Disambiguate obvious uses of effects.
category:            Polysemy

description:         Please see the README on GitHub at <https://github.com/polysemy-research/polysemy/tree/master/polysemy-plugin#readme>

dependencies:
- base
- ghc
- ghc-tcplugins-extra
- polysemy
- syb
- transformers
- containers

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest

library:
  source-dirs: src
  generated-other-modules:
  - Paths_polysemy_plugin

flags:
  corelint:
    description: Perform the corelint tests
    default:     False
    manual:      True

tests:
  polysemy-plugin-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    when:
    - condition: flag(corelint)
      ghc-options:
        - -dcore-lint
        - -dsuppress-all
    dependencies:
    - hspec-discover
    - polysemy
    - polysemy-plugin
    - hspec
    - should-not-typecheck
    - inspection-testing
    - doctest
    generated-other-modules:
    - Build_doctests

default-extensions:
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeFamilies

  - UnicodeSyntax
